// SOURCE DE VÉRITÉ — KIVOO
// Les subcats sont des strings = slug exact en DB (utilisé dans URL et filtre ads.subcategory)

export const CATEGORIES = [
  {
    id: 'cat_tech',
    name: 'High-Tech',
    icon: '📱',
    color: '#6366f1',
    subcats: [
      'telephones-accessoires',
      'ordinateurs',
      'tablettes',
      'tv-son',
      'photo-video',
      'consoles-jeux',
      'objets-connectes',
      'composants',
    ],
  },
  {
    id: 'cat_auto',
    name: 'Automobile',
    icon: '🚗',
    color: '#ef4444',
    subcats: [
      'voitures-d-occasion',
      'motos-scooters',
      'bateaux-nautisme',
      'pieces-detachees-pneus',
      'location-auto',
      'camions-utilitaires',
      'groupes-electrogenes',
      'outillage-industriel',
      'engins-chantier',
    ],
    requiresCertified: true,
  },
  {
    id: 'cat_immo',
    name: 'Immobilier',
    icon: '🏠',
    color: '#10b981',
    subcats: [
      'vente-appartement',
      'vente-maison-villa',
      'location-meublee',
      'maison-a-louer',
      'colocation',
      'terrains-acd',
      'bureaux-boutiques',
    ],
    requiresCertified: true,
  },
  {
    id: 'cat_serv',
    name: 'Services',
    icon: '🛠️',
    color: '#8b5cf6',
    subcats: [
      'freelance-it',
      'batiment',
      'cours-formation',
      'offres-emploi',
      'transport',
      'menage',
      'evenementiel',
    ],
  },
  {
    id: 'cat_maison',
    name: 'Maison & Équipement',
    icon: '🏡',
    color: '#06b6d4',
    subcats: ['meubles', 'electromenager', 'decoration', 'jardin-bricolage'],
  },
  {
    id: 'cat_mode',
    name: 'Mode & Accessoires',
    icon: '👕',
    color: '#f97316',
    subcats: ['vetements', 'chaussures', 'sacs-accessoires', 'montres', 'cosmetiques'],
  },
  {
    id: 'cat_beaute',
    name: 'Beauté & Bien-être',
    icon: '💄',
    color: '#ec4899',
    subcats: [
      'soins-visage',
      'soins-corps',
      'parfums',
      'complements-alimentaires',
      'materiel-coiffure',
    ],
  },
  {
    id: 'cat_sport',
    name: 'Sport & Loisirs',
    icon: '⚽',
    color: '#14b8a6',
    subcats: ['equipements-sport', 'instruments-musique', 'jouets', 'voyages', 'velos'],
  },
  {
    id: 'cat_autres',
    name: 'Autres & Divers',
    icon: '📦',
    color: '#64748b',
    subcats: ['animaux', 'fournitures-scolaires', 'collection', 'inclassables'],
  },
  {
    id: 'cat_adulte',
    name: 'Bien-être & Intimité',
    icon: '❤️',
    color: '#f43f5e',
    isAdult: true,
    subcats: [
      'lingerie-sous-vetements',
      'maillots-de-bain',
      'cosmetiques-bien-etre',
      'accessoires-mode',
    ],
  },
]

export const SUBCAT_LABELS: Record<string, string> = {
  // High-Tech
  'telephones-accessoires': 'Téléphones & Accessoires',
  'ordinateurs': 'Ordinateurs',
  'tablettes': 'Tablettes',
  'tv-son': 'TV & Son',
  'photo-video': 'Photo & Vidéo',
  'consoles-jeux': 'Consoles & Jeux',
  'objets-connectes': 'Objets Connectés',
  'composants': 'Composants',
  // Automobile
  'voitures-d-occasion': "Voitures d'Occasion",
  'motos-scooters': 'Motos & Scooters',
  'bateaux-nautisme': 'Bateaux & Nautisme',
  'pieces-detachees-pneus': 'Pièces & Pneus',
  'location-auto': 'Location Auto',
  'camions-utilitaires': 'Camions & Utilitaires',
  'groupes-electrogenes': 'Groupes Électrogènes',
  'outillage-industriel': 'Outillage Industriel',
  'engins-chantier': 'Engins de Chantier',
  // Immobilier
  'vente-appartement': 'Vente Appartement',
  'vente-maison-villa': 'Vente Maison & Villa',
  'location-meublee': 'Location Meublée',
  'maison-a-louer': 'Maison à Louer',
  'colocation': 'Colocation',
  'terrains-acd': 'Terrains & ACD',
  'bureaux-boutiques': 'Bureaux & Boutiques',
  // Services
  'freelance-it': 'Freelance & IT',
  'batiment': 'Bâtiment & Travaux',
  'cours-formation': 'Cours & Formation',
  'offres-emploi': 'Offres d\'Emploi',
  'transport': 'Transport',
  'menage': 'Ménage & Nettoyage',
  'evenementiel': 'Événementiel',
  // Maison
  'meubles': 'Meubles',
  'electromenager': 'Électroménager',
  'decoration': 'Décoration',
  'jardin-bricolage': 'Jardin & Bricolage',
  // Mode
  'vetements': 'Vêtements',
  'chaussures': 'Chaussures',
  'sacs-accessoires': 'Sacs & Accessoires',
  'montres': 'Montres',
  'cosmetiques': 'Cosmétiques',
  // Beauté
  'soins-visage': 'Soins Visage',
  'soins-corps': 'Soins Corps',
  'parfums': 'Parfums',
  'complements-alimentaires': 'Compléments Alimentaires',
  'materiel-coiffure': 'Matériel Coiffure',
  // Sport
  'equipements-sport': 'Équipements Sport',
  'instruments-musique': 'Instruments de Musique',
  'jouets': 'Jouets',
  'voyages': 'Voyages',
  'velos': 'Vélos',
  // Autres
  'animaux': 'Animaux',
  'fournitures-scolaires': 'Fournitures Scolaires',
  'collection': 'Collection',
  'inclassables': 'Inclassables',
  // Adulte
  'lingerie-sous-vetements': 'Lingerie & Sous-vêtements',
  'maillots-de-bain': 'Maillots de Bain',
  'cosmetiques-bien-etre': 'Cosmétiques Bien-être',
  'accessoires-mode': 'Accessoires Mode',
}

export const CITIES = [
  '🌍 Toute la CI',
  '🏙️ Abidjan',
  '🌇 Bouaké',
  '🏛️ Yamoussoukro',
  '⚓ San-Pédro',
  '🌳 Daloa',
  '🌴 Korhogo',
  '⛰️ Man',
  '🌊 Gagnoa',
]
