// SOURCE DE VERITE — AbidjanDeals
export const CATEGORIES = [
  {
    id: 'cat_tech',
    name: 'High-Tech',
    icon: '📱',
    color: '#6366f1',
    subcats: [
      'telephones-accessoires',
      'ordinateurs',
      'tablettes',
      'tv-son',
      'photo-video-cameras',
      'consoles-jeux',
      'objets-connectes',
      'composants',
    ],
  },
  {
    id: 'cat_auto',
    name: 'Automobile',
    icon: '🚗',
    color: '#ef4444',
    subcats: [
      'voitures-d-occasion',
      'voitures-neuves',
      'motos-scooters',
      'pieces-pneus',
      'location-auto',
      'camions-utilitaires',
      'groupes-electrogenes',
      'materiel-agricole',
      'outillage-industriel',
      'engins-chantier',
    ],
    requiresCertified: true,
  },
  {
    id: 'cat_immo',
    name: 'Immobilier',
    icon: '🏠',
    color: '#10b981',
    subcats: [
      'vente-appartement',
      'vente-maison-villa',
      'location-meublee',
      'location-vide',
      'location-saisonniere',
      'colocation',
      'terrains-acd',
      'bureaux-boutiques',
    ],
    requiresCertified: true,
  },
  {
    id: 'cat_serv',
    name: 'Services',
    icon: '🛠️',
    color: '#8b5cf6',
    subcats: [
      'freelance-it',
      'batiment',
      'cours-formation',
      'offres-emploi',
      'transport-livraison',
      'menage',
      'securite',
      'evenementiel',
      'services-divers',
    ],
  },
  {
    id: 'cat_maison',
    name: 'Maison & Equipement',
    icon: '🏡',
    color: '#06b6d4',
    subcats: ['meubles', 'electromenager', 'decoration', 'jardin-bricolage', 'autres-equipements'],
  },
  {
    id: 'cat_mode',
    name: 'Mode & Accessoires',
    icon: '👕',
    color: '#f97316',
    subcats: ['vetements-femme', 'vetements-homme', 'chaussures', 'sacs-accessoires', 'montres-bijoux'],
  },
  {
    id: 'cat_beaute',
    name: 'Beaute & Bien-etre',
    icon: '💄',
    color: '#ec4899',
    subcats: ['cosmetiques', 'parfums', 'soins-corps', 'coiffure-cheveux', 'complements-alimentaires'],
  },
  {
    id: 'cat_bebe',
    name: 'Bebe & Maman',
    icon: '🍼',
    color: '#f59e0b',
    subcats: ['vetements-bebe', 'chaussures-bebe', 'jouets-eveil', 'accessoires-bebe', 'articles-maman'],
  },
  {
    id: 'cat_epicerie',
    name: 'Epicerie & Produits locaux',
    icon: '🛒',
    color: '#84cc16',
    subcats: ['produits-alimentaires', 'boissons', 'produits-locaux'],
  },
  {
    id: 'cat_sport',
    name: 'Sport & Loisirs',
    icon: '⚽',
    color: '#14b8a6',
    subcats: ['equipements-sportifs', 'fitness-musculation', 'jeux-loisirs'],
  },
  {
    id: 'cat_adulte',
    name: 'Bien-etre & Intimite',
    icon: '❤️',
    color: '#f43f5e',
    isAdult: true,
    subcats: ['bien-etre-couple', 'lubrifiants-gels', 'hygiene-intime', 'accessoires-massage', 'accessoires-adultes'],
  },
]
export const CITIES = [
  '🌍 Toute la CI',
  '🏙️ Abidjan',
  '🌇 Bouake',
  '🏛️ Yamoussoukro',
  '⚓ San-Pedro',
  '🌳 Daloa',
  '🌴 Korhogo',
  '⛰️ Man',
  '🌊 Gagnoa',
]
